### ISSUE TITLE
报错：OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by MHYPS** [cndiandian/weibo#10]
在抓取博主发的真爱粉专属图片时，获取不到原图会一直重复抓取同一条微博，不能接着获取下一条微博。请问这能不能设置跳过啊？

**Comment by MHYPS** [comment]
不懂python (Ｔ▽Ｔ)
https://static01.imgkr.com/temp/5022259637b94575bd447ed35488362b.jpg

**Comment by xshwy** [comment]
0_0 忘记还有真爱粉图片这一个类型了，方便贴一下博主的id吗，我去增加一个判断。

**Comment by MHYPS** [comment]
只能针对特定的账号做判断吗？
微博博主ID：GoatsMilk奶卡羊


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cndiandian/weibo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月23日(星期三) 下午5:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cndiandian/weibo] 报错：OSError: [Errno 22] Invalid argument (Issue #10)





 
0_0 忘记还有真爱粉图片这一个类型了，方便贴一下博主的id吗，我去增加一个判断。

**Comment by MHYPS** [comment]
已发往邮箱

**Comment by MHYPS** [comment]
只能针对特定的账号做判断吗？
微博博主ID：GoatsMilk奶卡羊

**Comment by cndiandian** [comment]
抱歉最近有其他事情没顾得上同步github，刚才发现问题了，应该是文件名的问题，之前获取的文件名是干脆的通过url分割，获取?后面的所有字符串，就会导致一些特殊字符在Windows上无法作为文件名的存在，实际上与是否是真爱粉专属图片无关。
