### ISSUE TITLE
怎么获取别人的微博数字ID？

### ISSUE THREAD

**Issue by myartings** [cndiandian/weibo#13]

**Comment by cndiandian** [comment]
README中有提到 https://github.com/cndiandian/weibo#b5

**Comment by myartings** [comment]
这个是说自己的微博数字ID，别人的主页点击进去是没有ID信息的。

**Comment by myartings** [comment]
这个工具应该不是用来转发自己的微博动态吧？

**Comment by cndiandian** [comment]
在电脑上，点任意用户的头像进去，就可以看到了
<img width="419" alt="image" src="https://user-images.githubusercontent.com/68210661/188297903-2c75727e-0c45-498f-8dc3-b88248f7ad4e.png">

**Comment by myartings** [comment]
谢谢，发现大部分微博账号是可以看到的，不过有些不显示，有点奇怪。
<img width="1267" alt="Snipaste_2022-09-04_12-53-33" src="https://user-images.githubusercontent.com/4220108/188298109-0c77345d-5a8a-4b55-8574-b4657c29afc3.png">

**Comment by myartings** [comment]
谢谢，发现大部分微博账号是可以看到的，不过有些不显示，有点奇怪。
<img width="766" alt="Snipaste_2022-09-04_12-56-08" src="https://user-images.githubusercontent.com/4220108/188298131-0d6274f8-384e-4f97-9ac2-4f26f68237cb.png">
