### ISSUE TITLE
[報錯] KeyError: 'mblog' + [問題] 數學ID用英文逗號隔開都是不能用

### ISSUE THREAD

**Issue by michchan9527** [cndiandian/weibo#14]
[報錯]
Traceback (most recent call last):
  File "E:\weibo\weibo.py", line 205, in <module>
    weibo.run()
  File "E:\weibo\weibo.py", line 173, in run
    if item['mblog']['isLongText']: # 如果博文包含全文 则去解析完整微博
KeyError: 'mblog'
[問題]
只有一個ID就可以用,但兩個就說【错误】请重新测试或检查微博数字ID是否正确

**Comment by cndiandian** [comment]
感谢告知错误信息，刚刚已更新，经排查是在获取部分大V博主微博时，中间有一条数据是粉丝群相关的，JSON结构不对，所以抛出了异常，现已修复，请更新使用。
