### ISSUE TITLE
报错：UnboundLocalError: local variable 'weibo_items' referenced before assignment

### ISSUE THREAD

**Issue by irongu** [cndiandian/weibo#15]
按配置指导流程完成配置之后运行win_test，一直提示
`【错误】请重新测试或检查微博数字ID是否正确`

核对后确定微博数字ID无误，运行win_run，提示
```
2022-09-27 13:11:28 开始运行>>>
2022-09-27 13:11:28     |-开始获取 6026974244 的微博
2022-09-27 13:11:28     |-访问url出错了
Traceback (most recent call last):
  File "./weibo.py", line 208, in <module>
    weibo.run()
  File "./weibo.py", line 171, in run
    for item in weibo_items:
UnboundLocalError: local variable 'weibo_items' referenced before assignment
```
python版本是readme里提供的3.9.0，python小白，按百度搜索的结果自己尝试前后加了一下global声明，没有解决问题。感觉应该不是程序本身问题，希望能提供一些指导，谢谢！

**Comment by cndiandian** [comment]
你好 我在本地测试没有问题 麻烦添加一下 readme顶部的微信，帮忙测试一下看看

我的环境：
```
Python 3.9.13 (main, May 19 2022, 13:48:47)
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
```

**Comment by irongu** [comment]
之前编辑config文件的时候用的是宝塔面板自带的文件编辑功能，现在用notepad++重新编辑了个新的config文件，突然就可以了……
我猜可能是因为之前用的编辑器不正规导入了某些不可见字符，总之现在问题解决了，非常抱歉打扰您，感谢您优秀的项目。

**Comment by zhl111** [comment]
请教您，我运行win_test 为什么什么都不显示呢？
![image](https://user-images.githubusercontent.com/29135984/223314482-fa59e577-a217-43b9-83d8-3244107f8a20.png)
