### ISSUE TITLE
测试关于微博ID一直报错

### ISSUE THREAD

**Issue by Amanatsu7** [cndiandian/weibo#17]
[](url)抱歉打扰了，电脑小白，按照教程填写之后测试环节微博ID这块一直在报错

WEIBO_ID=7756834804

目前我是这么填写的.不知道报错的原因是什么。
![20221004135656](https://user-images.githubusercontent.com/114977085/193745389-6d94eb69-c596-4aa4-890e-eaf2c3539459.png)

**Comment by cndiandian** [comment]
微博修改了现有的接口，已发现新接口，正在测试可靠性。

**Comment by Amanatsu7** [comment]
> 微博现有的接口，已经有新的接口，正在测试中发现。

原来如此，辛苦了！
