### ISSUE TITLE
关注多个对象

### ISSUE THREAD

**Issue by githubacct001** [cndiandian/weibo#2]
看样子似乎已经很久没更新了 不知道是不是还有机会看到这个提议 目前似乎只能监控单个微博？不知道有没有机会更新监控多个微博对象

**Comment by cndiandian** [comment]
> 看样子似乎已经很久没更新了 不知道是不是还有机会看到这个提议 目前似乎只能监控单个微博？不知道有没有机会更新监控多个微博对象

是可以同时关注多个微博的，不过没有具体实现；你可以设置一个微博ID的list，在run函数里执行循环就可以，不过记得注意每次请求之间的间隔，给个几秒的延迟就可以，避免被新浪屏蔽。
