### ISSUE TITLE
订阅多个用户时，好像无法进行推送？

### ISSUE THREAD

**Issue by Tegfe** [cndiandian/weibo#23]
尝试填写了两个ID，发现新内容并没有进行推送，直接就执行结束了

**Comment by cndiandian** [comment]
现在还有类似问题吗，如果有，可以提供一下系统环境，以及测试一下单个ID是否可以正确推送

**Comment by Tegfe** [comment]
谢谢作者回复，现在没有了，已经能够正常推送了。

然后还有一个问题就是，如果微博内容超过9张图，就只能读取9张进行推送，其他的图片就无法推送，这个能否看看怎么解决😂（或者是我这边单个的问题）？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月05日 19:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [cndiandian/weibo] 订阅多个用户时，好像无法进行推送？ (Issue #23) |

现在还有类似问题吗，如果有，可以提供一下系统环境，以及测试一下单个ID是否可以正确推送

**Comment by cndiandian** [comment]
更新一下代码就可以啦，这个情况再8月份的时候修复了，更新后如果还有问题，请再次告知~
