### ISSUE TITLE
执行时遇到 UnboundLocalError: local variable 'weibo_items' referenced before assignment 问题

### ISSUE THREAD

**Issue by zhl111** [cndiandian/weibo#24]
由于cfw删库，我换了clash verge，就出了这个问题。除了代理之外我不知道还涉及什么方面，请教怎么解决呢？

![image](https://github.com/cndiandian/weibo/assets/29135984/231abc3f-f4ca-4402-aa4b-f61da5c2ba5e)

**Comment by xshwy** [comment]
`UnboundLocalError: local variable 'weibo_items' referenced before assignment`
之前有用户遇到过类似的问题，经排查发现，是在命令行里面没有访问外网的权限

解决方案：
当时用户使用的是Clash for Windows，勾选「Specify Protocol」后就可以正常访问使用了，可以尝试在Clash Verge中查找类似的选项，勾选即可使用。

排查步骤：
如果有代码开发能力，可以尝试在 ipython中通过requests访问 google 或者 tg的api接口，如果可以访问，那应该就可以使用了。

![x12Frame 7](https://github.com/cndiandian/weibo/assets/1038801/dd008007-bc49-404c-8b4b-981239645911)

**Comment by cndiandian** [comment]
`UnboundLocalError: local variable 'weibo_items' referenced before assignment`
之前有用户遇到过类似的问题，经排查发现，是在命令行里面没有访问外网的权限

解决方案：
当时用户使用的是Clash for Windows，勾选「Specify Protocol」后就可以正常访问使用了，可以尝试在Clash Verge中查找类似的选项，勾选即可使用。

排查步骤：
如果有代码开发能力，可以尝试在 ipython中通过requests访问 google 或者 tg的api接口，如果可以访问，那应该就可以使用了。

![x12Frame 7](https://github.com/cndiandian/weibo/assets/1038801/dd008007-bc49-404c-8b4b-981239645911)
