### ISSUE TITLE
小白部署到vps上不会了

### ISSUE THREAD

**Issue by zhl111** [cndiandian/weibo#25]
我安装到vps了，但到要运行`python weibo.py`这就不行了，还望指导一二

**Comment by xshwy** [comment]
在linux上部署，可能同时存在python2和python3，部分系统执行python默认是执行的python2，可以尝试用 pip3 安装依赖，通过`python3 weibo.py`来进行执行爬取

**Comment by cndiandian** [comment]
在linux上部署，可能同时存在python2和python3，部分系统执行python默认是执行的python2，可以尝试用 `pip3 install -r requirements.txt` 安装依赖，通过`python3 weibo.py` 来进行执行

**Comment by zhl111** [comment]
太感谢了，能成功运行了，但如果想在vps上自动运行的话，我还要做什么呢？我执行了`crontab -e`
![image](https://github.com/cndiandian/weibo/assets/29135984/c67d0451-93ce-40ff-8950-5728b425d5c4)
得到：`crontab: installing new crontab` ，这算是成功了吗？

**Comment by cndiandian** [comment]
在crontab里面需要按照下面的格式填写
把 ` /usr/bin/python3` 换成你的系统python环境（默认用这个大概率也行）
把 `/home/weibo/` 换成你weibo.py所在的目录


`* * * * * /usr/bin/python3 -u /home/weibo/weibo.py >> /home/weibo/weibo.log 2>&1`

**Comment by zhl111** [comment]
感谢，能自动运行了。但发现有时候获取的微博信息经常重复获取，这是什么情况呢？
