### ISSUE TITLE
现在需要cookie了吧

### ISSUE THREAD

**Issue by mikudate** [cndiandian/weibo#27]
微博现在又无法让游客看了。

**Comment by cndiandian** [comment]
近期多次测试，`https://m.weibo.cn/u/…` 与 `https://weibo.com/u/…`还是可以匿名访问的，只是访问条数有限，如果定时执行的话，可以一直拉到最新的数据。

如果确实无法访问，请尝试提供一下相关的截图，以及网络信息。
