### ISSUE TITLE
Bug: 当某微博内容拥有超过9张图片时，bot 仅转发了前 9 张图片。

### ISSUE THREAD

**Issue by XmJwit** [cndiandian/weibo#5]
另外一个小建议就是，转发微博时，bot 发送的消息可否整成图文格式，即单消息的格式？

**Comment by cndiandian** [comment]
增加对折叠全文的支持，以及针对全文的18张全部图片的支持；非全文的18张图暂时没做调整，不确定是否有支持。

**Comment by cndiandian** [comment]
已支持超过9张图片。
