### ISSUE TITLE
能否添加cookie登录？

### ISSUE THREAD

**Issue by End-Satan** [cndiandian/weibo#7]
因为很多只能抓取部分一点点内容

**Comment by cndiandian** [comment]
`很多只能抓取部分一点点内容` 指的是哪方面？是说某一条微博只能读取一部分吗？还是什么呢？麻烦提供一下相关截图以及链接，

**Comment by End-Satan** [comment]
> 

就是我抓取别人账号的内容，只能抓取一两条微博内容，而且抓取微博的也不是按照最新发表是顺序抓取的。比较乱

**Comment by End-Satan** [comment]
不是抓取原图的吧？抓取gif图片结果都是jpg的

**Comment by cndiandian** [comment]
提供一下相关的结果截图、相关微博的url链接，不方便公开贴的话，在README.md中加我微信私发，备注「github 微博」

**Comment by End-Satan** [comment]
比如我抓取刘亦菲的，只能抓取几条，而且都没抓取到
![1](https://user-images.githubusercontent.com/17049937/151826476-b0921292-6040-4cbc-be67-038d471b91e4.png)
![2](https://user-images.githubusercontent.com/17049937/151826489-7525fdc9-f054-430f-878f-812eab136cec.png)
![3](https://user-images.githubusercontent.com/17049937/151826497-6b930584-3ec0-44cb-b5fe-9eb2ae19f04a.png)

**Comment by cndiandian** [comment]
我实际尝试了一下，是可以获取到最近的十条内容以及相关配图的，这个bot的作用也就是只能获取最近10条，然后不停的去扫描是否有新的内容，这样就可以实现从你添加之日起，一直订阅。
