### ISSUE TITLE
请问报错怎么解决？

### ISSUE THREAD

**Issue by redto-mato** [cndiandian/weibo#9]
UnicodeEncodeError: 'local' code can't encode character '\u6267' in position 18: encoding error

**Comment by cndiandian** [comment]
看起来是编码错误，请问一下是在什么系统上运行的，以及是每条微博都是这样，还是个别微博。

**Comment by cndiandian** [comment]
方便的话麻烦把全部的报错信息也发一下，如果涉及隐私的话麻烦加我微信提供一下，微信在README中有。

**Comment by redto-mato** [comment]
试了2个账号，报错是一样的

[https://tva1.sinaimg.cn/large/6111f088ly1h080hy2auuj20rl0ef4a6.jpg](url)
[https://tvax1.sinaimg.cn/large/6111f088ly1h080k51kysj20d9069q3a.jpg](url)

**Comment by cndiandian** [comment]
差不多是有解决方案了 需要你帮忙测试一下，麻烦在README中加个微信吧，备注 github weibo
